# Simplified Digital Ocean App Platform Spec for ENACT Hyku
# Start with essential services only

name: enact-hyku
region: lon

# Services Configuration
services:
  # Web Application (Rails)
  - name: web
    github:
      repo: adammoore/enact-hyku
      branch: main
      deploy_on_push: true
    dockerfile_path: Dockerfile
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xs
    health_check:
      http_path: /health
      initial_delay_seconds: 60
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    envs:
      - key: RAILS_ENV
        value: production
      - key: SECRET_KEY_BASE
        scope: RUN_AND_BUILD_TIME
        value: "760e18d6de5eeea8ce99ad914b0f0e68ad7ad6dd2140a58b831fb425cea8c00db2e26a87c1523599eec7f2b03746aee959a9b07e6a49b1b5d7413a9253258eee"
      - key: DISABLE_SPRING
        value: "1"
      - key: ASSETS_PRECOMPILE
        scope: BUILD_TIME
        value: "true"
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
      - key: RAILS_SERVE_STATIC_FILES
        value: "true"
      - key: HYKU_MULTITENANT
        value: "true"
      - key: HYKU_ADMIN_ONLY_TENANT_CREATION
        value: "true"
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db.DATABASE_URL}
      - key: REDIS_URL
        value: redis://redis:6379/0
      - key: SOLR_URL
        value: http://solr:8983/solr/

  # Solr Search Engine
  - name: solr
    github:
      repo: adammoore/enact-hyku
      branch: main
      deploy_on_push: true
    dockerfile_path: Dockerfile
    build_command: docker build --target hyku-solr -t $IMAGE_NAME .
    instance_count: 1
    instance_size_slug: basic-xxs
    internal_ports:
      - 8983

  # Redis Cache
  - name: redis
    image:
      registry_type: DOCKER_HUB
      registry: library
      repository: redis
      tag: "7-alpine"
    instance_count: 1
    instance_size_slug: basic-xxs
    internal_ports:
      - 6379

# Databases
databases:
  - name: db
    engine: PG
    version: "15"
    production: false
