# Digital Ocean App Platform Specification for ENACT Hyku
# Deploy full Samvera Hyku stack with PRVoices schema support

name: enact-hyku
region: lon

# Services Configuration
services:
  # Web Application (Rails)
  - name: web
    github:
      repo: adammoore/enact-hyku
      branch: main
      deploy_on_push: true
    dockerfile_path: Dockerfile
    http_port: 3000
    instance_count: 1
    instance_size_slug: professional-s
    health_check:
      http_path: /
    envs:
      - key: RAILS_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
      - key: RAILS_SERVE_STATIC_FILES
        value: "true"
      - key: HYKU_MULTITENANT
        value: "true"
      - key: HYKU_ADMIN_ONLY_TENANT_CREATION
        value: "true"
      - key: HYKU_ADMIN_HOST
        value: ${APP_DOMAIN}
      - key: HYKU_ROOT_HOST
        value: ${APP_DOMAIN}
      - key: SECRET_KEY_BASE
        type: SECRET
        value: ${SECRET_KEY_BASE}
      - key: DATABASE_URL
        value: ${db.DATABASE_URL}
      - key: REDIS_URL
        value: ${redis.REDIS_URL}
      - key: SOLR_URL
        value: http://solr:8983/solr/hyku
      - key: FEDORA_URL
        value: http://fcrepo:8080/fcrepo/rest
      - key: AWS_ACCESS_KEY_ID
        type: SECRET
        value: ${AWS_ACCESS_KEY_ID}
      - key: AWS_SECRET_ACCESS_KEY
        type: SECRET
        value: ${AWS_SECRET_ACCESS_KEY}
      - key: AWS_REGION
        value: ${AWS_REGION}
      - key: AWS_BUCKET
        value: ${AWS_BUCKET}
      - key: SMTP_ADDRESS
        value: ${SMTP_ADDRESS}
      - key: SMTP_PORT
        value: ${SMTP_PORT}
      - key: SMTP_USER_NAME
        type: SECRET
        value: ${SMTP_USER_NAME}
      - key: SMTP_PASSWORD
        type: SECRET
        value: ${SMTP_PASSWORD}

  # Background Workers (Sidekiq)
  - name: worker
    github:
      repo: adammoore/enact-hyku
      branch: main
      deploy_on_push: true
    dockerfile_path: Dockerfile
    run_command: bundle exec sidekiq
    instance_count: 1
    instance_size_slug: basic-xs
    envs:
      - key: RAILS_ENV
        value: production
      - key: DATABASE_URL
        value: ${db.DATABASE_URL}
      - key: REDIS_URL
        value: ${redis.REDIS_URL}
      - key: SOLR_URL
        value: http://solr:8983/solr/hyku
      - key: FEDORA_URL
        value: http://fcrepo:8080/fcrepo/rest
      - key: SECRET_KEY_BASE
        type: SECRET
        value: ${SECRET_KEY_BASE}
      - key: SIDEKIQ_CONCURRENCY
        value: "5"

  # Solr Search Service
  - name: solr
    image:
      registry_type: DOCKER_HUB
      registry: library
      repository: solr
      tag: "8"
    instance_count: 1
    instance_size_slug: basic-s
    internal_ports:
      - 8983
    run_command: |
      solr-precreate hyku /opt/solr/server/solr/configsets/_default
    envs:
      - key: SOLR_HEAP
        value: 1g

  # Fedora Repository
  - name: fcrepo
    image:
      registry_type: DOCKER_HUB
      registry: samvera
      repository: fcrepo4
      tag: "4.7.6"
    instance_count: 1
    instance_size_slug: basic-s
    internal_ports:
      - 8080
    envs:
      - key: CATALINA_OPTS
        value: -Djava.awt.headless=true -Dfile.encoding=UTF-8 -server -Xms512m -Xmx1024m -XX:NewSize=256m -XX:MaxNewSize=256m -XX:PermSize=256m -XX:MaxPermSize=256m -XX:+DisableExplicitGC

# Databases and Caches
databases:
  - name: db
    engine: PG
    version: "15"
    production: true
    cluster_name: enact-hyku-db

  - name: redis
    engine: REDIS
    version: "7"
    production: true

# Jobs (one-time tasks)
jobs:
  - name: db-migrate
    kind: PRE_DEPLOY
    github:
      repo: adammoore/enact-hyku
      branch: main
    dockerfile_path: Dockerfile
    run_command: bundle exec rails db:migrate
    envs:
      - key: RAILS_ENV
        value: production
      - key: DATABASE_URL
        value: ${db.DATABASE_URL}
